
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: office_rent_frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - office_rent_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: office_rent_backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - office_rent_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: office_rent_db
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - office_rent_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: office_rent_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - frontend
      - backend
    networks:
      - office_rent_network

  mailhog:
    image: mailhog/mailhog
    container_name: office_rent_mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    networks:
      - office_rent_network

networks:
  office_rent_network:
    driver: bridge

volumes:
  mysql_data:
