apiVersion: 1

deleteDatasources:
  - name: Office Rent Prometheus
    orgId: 1
  - name: Office Rent Loki
    orgId: 1
  - name: Office Rent MySQL
    orgId: 1

datasources:
  - name: Office Rent Prometheus
    uid: office-rent-prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: Office Rent Loki
    uid: office-rent-loki
    orgId: 1
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000

  - name: Office Rent MySQL
    uid: office-rent-mysql
    orgId: 1
    type: mysql
    access: proxy
    url: ${DB_HOST}:${DB_PORT}
    user: ${DB_USERNAME}
    editable: true
    jsonData:
      database: ${DB_DATABASE}
      maxOpenConns: 20
      maxIdleConns: 5
      connMaxLifetime: 14400
      timeInterval: 1m
    secureJsonData:
      password: ${DB_PASSWORD}
