apiVersion: 1

datasources:
  - name: Office Rent MySQL
    uid: office-rent-mysql
    type: mysql
    access: proxy
    url: ${DB_HOST}:${DB_PORT}
    user: ${DB_USERNAME}
    isDefault: true
    editable: true
    jsonData:
      database: ${DB_DATABASE}
      maxOpenConns: 20
      maxIdleConns: 5
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      timeInterval: 1m
    secureJsonData:
      password: ${DB_PASSWORD}
