import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  id: {
    // Navbar
    nav_home: 'Beranda',
    nav_rooms: 'Daftar Ruangan',
    nav_popular: 'Populer',
    nav_my_orders: 'Pesanan Saya',
    nav_profile: 'Profil',
    nav_admin: 'Admin',
    nav_logout: 'Keluar',
    nav_login: 'Masuk',
    nav_register: 'Daftar',

    // Hero
    hero_badge: 'Gedung Wisma 46, Kota BNI Jakarta',
    hero_title: 'Sewa Ruang Kerja Wisma 46',
    hero_subtitle: 'Office suite, meeting room, dan coworking space premium di gedung pencakar langit ikonik Jakarta — lokasi strategis, fasilitas kelas dunia.',
    hero_cta: 'Lihat Ruangan Tersedia',

    // Home sections
    home_latest_title: 'Ruangan Terbaru Wisma 46',
    home_latest_subtitle: 'Pilihan ruang terbaru yang tersedia untuk disewa di Wisma 46.',
    home_popular_btn: 'Ruangan Populer',
    home_see_all: 'Lihat Semua',
    home_reviews_title: 'Ulasan Penyewa Wisma 46',
    home_reviews_subtitle: 'Pengalaman nyata dari pelaku bisnis yang telah menyewa ruang di Wisma 46 — gedung bergengsi di jantung CBD Jakarta.',
    home_no_reviews: 'Belum ada ulasan yang ditampilkan.',
    home_tenant_of: 'Penyewa',

    // Room card & General
    capacity: 'Kapasitas',
    people: 'orang',
    start_from: 'Mulai dari',
    per_day: '/hari',
    detail: 'Detail',
    status_available: 'Tersedia',
    status_full: 'Dibook',
    status_maintenance: 'Pemeliharaan',
    status_booked_until: 'Dibook sampai',
    availability_info: 'Informasi Ketersediaan:',
    room_booked_until: 'Ruangan ini sudah dibook sampai tanggal',
    room_booked_after: 'Anda tetap dapat memesannya untuk tanggal setelah periode tersebut.',
    all: 'Semua',
    status: 'Status',
    capacity_label: 'Kapasitas:',
    capacity_people: 'orang',
    try_again: 'Coba Lagi',
    save_changes: 'Simpan Perubahan',
    loading: 'Memuat...',
    submitting: 'Memproses...',
    back_to_home_btn: 'Kembali ke Beranda',
    not_found_title: 'Halaman Tidak Ditemukan',
    not_found_desc: 'Maaf, halaman yang Anda cari tidak tersedia atau telah dipindahkan. Silakan kembali ke beranda untuk melanjutkan penelusuran ruangan.',
    yes: 'Ya',
    no: 'Tidak',

    // Daftar Ruangan
    rooms_title: 'Daftar Ruangan',
    rooms_subtitle: 'Temukan ruang kerja ideal di Wisma 46 yang sesuai kebutuhan bisnis Anda.',
    search_placeholder: 'Cari nama ruangan...',
    filter_all_categories: 'Semua Kategori',
    filter_all_status: 'Semua Status',
    sort_by: 'Urutkan:',
    sort_price_asc: 'Harga Terendah',
    sort_price_desc: 'Harga Tertinggi',
    sort_name_asc: 'Nama A-Z',
    sort_name_desc: 'Nama Z-A',
    no_rooms_found: 'Tidak ada ruangan yang sesuai kriteria pencarian Anda.',
    browse_rooms_title: 'Daftar Ruangan',
    browse_rooms_subtitle: 'Temukan ruang kerja terbaik yang sesuai dengan kebutuhan profesional Anda.',
    popular_page_title: 'Ruangan Populer',
    popular_page_subtitle: 'Koleksi ruangan terbaik yang paling banyak diminati oleh pengguna kami.',
    no_popular_rooms: 'Belum ada ruangan populer',
    no_popular_rooms_desc: 'Admin belum menandai ruangan manapun sebagai populer.',
    view_all_rooms: 'Lihat Semua Ruangan',
    fail_load_rooms: 'Gagal memuat data ruangan',
    fail_load_popular: 'Gagal memuat ruangan populer',
    please_check_connection: 'Pastikan koneksi internet Anda stabil dan coba lagi.',
    please_try_again_later: 'Silakan coba kembali dalam beberapa saat.',
    search_not_found: 'Ruangan tidak ditemukan',
    search_not_found_desc: 'Silakan coba kata kunci pencarian atau kategori yang lain.',

    // Popular
    popular_title: 'Ruangan Paling Populer',
    popular_subtitle: 'Ruangan favorit penyewa di Wisma 46 berdasarkan jumlah ulasan terbaik.',

    // Footer
    footer_address: 'Kota BNI, Jl. Jend. Sudirman Kav. 1, Jakarta 10220',
    footer_desc: 'Platform resmi penyewaan Office, Meeting Room, dan Coworking Space premium di gedung ikonik Wisma 46 — jantung bisnis Jakarta.',
    footer_copyright: 'Wisma 46 Space. Hak Cipta Dilindungi.',

    // Login
    login_title: 'Selamat Datang',
    login_subtitle: 'Masuk ke akun Anda untuk melanjutkan',
    login_email: 'Email',
    login_password: 'Password',
    login_forgot: 'Lupa Password?',
    login_btn: 'Masuk',
    login_no_account: 'Belum punya akun?',
    login_register_link: 'Daftar sekarang',
    back_to_home: 'Kembali ke Beranda',

    // Register
    register_title: 'Buat Akun Baru',
    register_subtitle: 'Daftar untuk mulai menyewa ruangan',
    register_name: 'Nama Lengkap',
    register_btn: 'Daftar',
    register_has_account: 'Sudah punya akun?',
    register_login_link: 'Masuk di sini',

    // Detail Ruangan
    book_now: 'Pesan Sekarang',
    facilities: 'Fasilitas',
    reviews: 'Ulasan',
    addons: 'Tambahan (Add-on)',
    no_reviews_yet: 'Belum ada ulasan untuk ruangan ini.',
    please_login: 'Silakan login untuk memesan.',
    limited_access_title: 'Akses Terbatas untuk',
    limited_access_desc: 'hanya memiliki akses ke panel operasional. Pemesanan ruangan dilakukan oleh pengguna terdaftar.',
    go_to_panel: 'Pergi ke Panel',
    duration_days: 'Durasi (Hari)',
    start_date: 'Tanggal Mulai',
    end_date: 'Tanggal Selesai (Estimasi)',
    start_time: 'Waktu Mulai',
    end_time: 'Waktu Selesai',
    order_details: 'Detail Pemesanan',
    price_per_day: 'Harga per Hari',
    subtotal: 'Subtotal',
    coupon_applied: 'Kupon Berhasil Diterapkan',
    apply_coupon: 'Gunakan Kupon',
    coupon_placeholder: 'Kode Kupon',
    apply_btn: 'Terapkan',
    total_payment: 'Total Pembayaran',
    customer_name: 'Nama Pemesan',
    customer_name_placeholder: 'Masukkan nama pemesan',
    company_name: 'Nama Perusahaan',
    company_name_placeholder: 'Masukkan nama perusahaan',
    agree_terms: 'Saya menyetujui syarat & ketentuan sewa ruangan.',
    success_booking: 'Pemesanan Berhasil!',
    booking_redirect: 'Mengalihkan Anda ke halaman detail pesanan...',
    booking_failed: 'Gagal melakukan pemesanan ruangan.',
    room_not_found: 'Ruangan tidak ditemukan',
    room_not_found_desc: 'Maaf, ruangan yang Anda cari tidak tersedia atau telah dihapus.',
    write_review: 'Tulis Ulasan Anda',
    submit_review: 'Kirim Ulasan',
    anonymous: 'Anonim',
    rating: 'Penilaian:',
    enter_review_comment: 'Tulis komentar ulasan Anda di sini...',
    review_success: 'Ulasan berhasil dikirim!',
    review_failed: 'Gagal mengirimkan ulasan.',

    // Profile Page
    profile_settings: 'Pengaturan Profil',
    profile_desc: 'Kelola informasi akun dan keamanan Anda',
    profile_personal_info: 'Informasi Pribadi',
    profile_full_name: 'Nama Lengkap',
    profile_email_address: 'Alamat Email',
    profile_security: 'Keamanan Password',
    profile_current_password: 'Password Sekarang',
    profile_current_password_placeholder: 'Masukkan password saat ini',
    profile_new_password: 'Password Baru',
    profile_new_password_placeholder: 'Minimal 6 karakter',
    profile_confirm_password: 'Konfirmasi Password',
    profile_confirm_password_placeholder: 'Ulangi password baru',
    profile_update_success: 'Profil berhasil diperbarui!',
    profile_update_failed: 'Gagal memperbarui profil',
    password_change_success: 'Password berhasil diubah!',
    password_change_failed: 'Gagal mengubah password',
    change_password_btn: 'Ganti Password',

    // Pesanan Saya
    my_bookings_title: 'Pesanan Saya',
    my_bookings_subtitle: 'Kelola riwayat pemesanan ruangan Anda di Wisma 46',
    booking_id: 'ID Pemesanan',
    room_name: 'Nama Ruangan',
    booking_date: 'Tanggal Sewa',
    duration: 'Durasi',
    total_price: 'Total Harga',
    booking_status: 'Status',
    booking_action: 'Aksi',
    no_bookings: 'Belum ada riwayat pemesanan',
    no_bookings_desc: 'Anda belum memesan ruangan apapun. Silakan jelajahi ruangan kami.',
    order_now: 'Pesan Sekarang',
    status_pending: 'Menunggu',
    status_confirmed: 'Dikonfirmasi',
    status_canceled: 'Dibatalkan',
    status_completed: 'Selesai',
    extension: 'Perpanjangan',
    months: 'Bulan',
    extend: 'Perpanjang',
    booking_not_found: 'Pesanan Tidak Ditemukan',
    fail_load_bookings: 'Gagal memuat pesanan Anda',

    // Detail Pesanan
    order_detail_title: 'Detail Pemesanan #',
    order_detail_subtitle: 'Informasi lengkap mengenai status dan detail pemesanan Anda',
    back_to_my_orders: 'Kembali ke Pesanan Saya',
    booking_info: 'Informasi Pemesanan',
    booked_room: 'Ruangan yang Dipesan',
    category: 'Kategori',
    renter_info: 'Informasi Penyewa',
    renter_name: 'Nama Penyewa',
    company: 'Perusahaan',
    duration_value: 'Hari',
    addons_selected: 'Layanan Tambahan yang Dipilih',
    no_addons: 'Tidak ada tambahan',
    payment_info: 'Rincian Pembayaran',
    applied_coupon: 'Kupon yang Digunakan',
    discount: 'Diskon',
    cancel_booking: 'Batalkan Pemesanan',
    cancel_confirm: 'Apakah Anda yakin ingin membatalkan pemesanan ini?',
    cancel_success: 'Pemesanan berhasil dibatalkan.',
    cancel_failed: 'Gagal membatalkan pemesanan.',

    // Admin
    admin_dashboard: 'Dashboard',
    admin_rooms: 'Kelola Ruangan',
    admin_orders: 'Kelola Pemesanan',
    admin_reviews: 'Moderasi Ulasan',
    admin_coupons: 'Kelola Kupon',
    admin_back: 'Kembali ke Web',
  },

  en: {
    // Navbar
    nav_home: 'Home',
    nav_rooms: 'Browse Rooms',
    nav_popular: 'Popular',
    nav_my_orders: 'My Bookings',
    nav_profile: 'Profile',
    nav_admin: 'Admin',
    nav_logout: 'Sign Out',
    nav_login: 'Sign In',
    nav_register: 'Register',

    // Hero
    hero_badge: 'Wisma 46 Building, Kota BNI Jakarta',
    hero_title: 'Rent Workspace Wisma 46',
    hero_subtitle: 'Premium office suites, meeting rooms, and coworking spaces in Jakarta\'s iconic skyscraper — Business District Location, world-class facilities.',
    hero_cta: 'View Available Rooms',

    // Home sections
    home_latest_title: 'Newest Rooms Wisma 46',
    home_latest_subtitle: 'Newly available spaces ready for rent at Wisma 46.',
    home_popular_btn: 'Popular Rooms',
    home_see_all: 'See All',
    home_reviews_title: 'Tenant Reviews',
    home_reviews_subtitle: 'Real experiences from business professionals who have rented at Wisma 46 — Jakarta\'s most prestigious address.',
    home_no_reviews: 'No reviews to display yet.',
    home_tenant_of: 'Tenant at',

    // Room card & General
    capacity: 'Capacity',
    people: 'people',
    start_from: 'Starting from',
    per_day: '/day',
    detail: 'Detail',
    status_available: 'Available',
    status_full: 'Booked',
    status_maintenance: 'Maintenance',
    status_booked_until: 'Booked until',
    availability_info: 'Availability Info:',
    room_booked_until: 'This room is already booked until',
    room_booked_after: 'You can still book it for dates after this period.',
    all: 'All',
    status: 'Status',
    capacity_label: 'Capacity:',
    capacity_people: 'people',
    try_again: 'Try Again',
    save_changes: 'Save Changes',
    loading: 'Loading...',
    submitting: 'Processing...',
    back_to_home_btn: 'Back to Home',
    not_found_title: 'Page Not Found',
    not_found_desc: 'Sorry, the page you are looking for does not exist or has been moved. Please return to the homepage to continue browsing rooms.',
    yes: 'Yes',
    no: 'No',

    // Daftar Ruangan
    rooms_title: 'Browse Rooms',
    rooms_subtitle: 'Find the perfect workspace at Wisma 46 tailored to your business needs.',
    search_placeholder: 'Search room name...',
    filter_all_categories: 'All Categories',
    filter_all_status: 'All Status',
    sort_by: 'Sort by:',
    sort_price_asc: 'Lowest Price',
    sort_price_desc: 'Highest Price',
    sort_name_asc: 'Name A-Z',
    sort_name_desc: 'Name Z-A',
    no_rooms_found: 'No rooms match your search criteria.',
    browse_rooms_title: 'Browse Rooms',
    browse_rooms_subtitle: 'Find the best workspace suited to your professional needs.',
    popular_page_title: 'Popular Rooms',
    popular_page_subtitle: 'Collection of our most preferred and highly demanded workspaces.',
    no_popular_rooms: 'No Popular Rooms Yet',
    no_popular_rooms_desc: 'Administrator hasn\'t marked any rooms as popular.',
    view_all_rooms: 'View All Rooms',
    fail_load_rooms: 'Failed to load rooms data',
    fail_load_popular: 'Failed to load popular rooms',
    please_check_connection: 'Please make sure your internet connection is stable and try again.',
    please_try_again_later: 'Please try again in a few moments.',
    search_not_found: 'Rooms Not Found',
    search_not_found_desc: 'Please try another search keyword or category.',

    // Popular
    popular_title: 'Most Popular Rooms',
    popular_subtitle: 'Tenant favorites at Wisma 46 based on top ratings and reviews.',

    // Footer
    footer_address: 'Kota BNI, Jl. Jend. Sudirman Kav. 1, Jakarta 10220',
    footer_desc: 'The official rental platform for premium Office, Meeting Room, and Coworking Space at the iconic Wisma 46 — the heart of Jakarta\'s business district.',
    footer_copyright: 'Wisma 46 Space. All Rights Reserved.',

    // Login
    login_title: 'Welcome Back',
    login_subtitle: 'Sign in to your account to continue',
    login_email: 'Email',
    login_password: 'Password',
    login_forgot: 'Forgot Password?',
    login_btn: 'Sign In',
    login_no_account: 'Don\'t have an account?',
    login_register_link: 'Register now',
    back_to_home: 'Back to Home',

    // Register
    register_title: 'Create an Account',
    register_subtitle: 'Register to start booking rooms',
    register_name: 'Full Name',
    register_btn: 'Register',
    register_has_account: 'Already have an account?',
    register_login_link: 'Sign in here',

    // Detail Ruangan
    book_now: 'Book Now',
    facilities: 'Facilities',
    reviews: 'Reviews',
    addons: 'Add-ons',
    no_reviews_yet: 'No reviews for this room yet.',
    please_login: 'Please sign in to make a booking.',
    limited_access_title: 'Limited Access for',
    limited_access_desc: 'only has access to the operational panel. Room bookings are made by registered users.',
    go_to_panel: 'Go to Panel',
    duration_days: 'Duration (Days)',
    start_date: 'Start Date',
    end_date: 'End Date (Estimate)',
    start_time: 'Start Time',
    end_time: 'End Time',
    order_details: 'Booking Details',
    price_per_day: 'Price per Day',
    subtotal: 'Subtotal',
    coupon_applied: 'Coupon Applied Successfully',
    apply_coupon: 'Use Coupon',
    coupon_placeholder: 'Coupon Code',
    apply_btn: 'Apply',
    total_payment: 'Total Payment',
    customer_name: 'Renter Name',
    customer_name_placeholder: 'Enter renter name',
    company_name: 'Company Name',
    company_name_placeholder: 'Enter company name',
    agree_terms: 'I agree to the terms and conditions of room rental.',
    success_booking: 'Booking Successful!',
    booking_redirect: 'Redirecting you to booking details...',
    booking_failed: 'Failed to make a room booking.',
    room_not_found: 'Room Not Found',
    room_not_found_desc: 'Sorry, the room you are looking for is not available or has been deleted.',
    write_review: 'Write Your Review',
    submit_review: 'Submit Review',
    anonymous: 'Anonymous',
    rating: 'Rating:',
    enter_review_comment: 'Write your review comment here...',
    review_success: 'Review submitted successfully!',
    review_failed: 'Failed to submit review.',

    // Profile Page
    profile_settings: 'Profile Settings',
    profile_desc: 'Manage your account information and security',
    profile_personal_info: 'Personal Information',
    profile_full_name: 'Full Name',
    profile_email_address: 'Email Address',
    profile_security: 'Password Security',
    profile_current_password: 'Current Password',
    profile_current_password_placeholder: 'Enter current password',
    profile_new_password: 'New Password',
    profile_new_password_placeholder: 'Min 6 characters',
    profile_confirm_password: 'Confirm Password',
    profile_confirm_password_placeholder: 'Repeat new password',
    profile_update_success: 'Profile updated successfully!',
    profile_update_failed: 'Failed to update profile',
    password_change_success: 'Password changed successfully!',
    password_change_failed: 'Failed to change password',
    change_password_btn: 'Change Password',

    // Pesanan Saya
    my_bookings_title: 'My Bookings',
    my_bookings_subtitle: 'Manage your room booking history at Wisma 46',
    booking_id: 'Booking ID',
    room_name: 'Room Name',
    booking_date: 'Rental Date',
    duration: 'Duration',
    total_price: 'Total Price',
    booking_status: 'Status',
    booking_action: 'Action',
    no_bookings: 'No booking history yet',
    no_bookings_desc: 'You have not booked any rooms yet. Please explore our spaces.',
    order_now: 'Book Now',
    status_pending: 'Pending',
    status_confirmed: 'Confirmed',
    status_canceled: 'Canceled',
    status_completed: 'Completed',
    extension: 'Extension',
    months: 'Months',
    extend: 'Extend',
    booking_not_found: 'Booking Not Found',
    fail_load_bookings: 'Failed to load your bookings',

    // Detail Pesanan
    order_detail_title: 'Booking Details #',
    order_detail_subtitle: 'Complete information regarding your booking status and details',
    back_to_my_orders: 'Back to My Bookings',
    booking_info: 'Booking Information',
    booked_room: 'Booked Room',
    category: 'Category',
    renter_info: 'Renter Information',
    renter_name: 'Renter Name',
    company: 'Company',
    duration_value: 'Days',
    addons_selected: 'Selected Add-on Services',
    no_addons: 'No add-ons',
    payment_info: 'Payment Details',
    applied_coupon: 'Applied Coupon',
    discount: 'Discount',
    cancel_booking: 'Cancel Booking',
    cancel_confirm: 'Are you sure you want to cancel this booking?',
    cancel_success: 'Booking canceled successfully.',
    cancel_failed: 'Failed to cancel booking.',

    // Admin
    admin_dashboard: 'Dashboard',
    admin_rooms: 'Manage Rooms',
    admin_orders: 'Manage Bookings',
    admin_reviews: 'Moderate Reviews',
    admin_coupons: 'Manage Coupons',
    admin_back: 'Back to Website',
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'id');

  const toggleLang = () => {
    const next = lang === 'id' ? 'en' : 'id';
    setLang(next);
    localStorage.setItem('lang', next);
  };

  const t = (key) => translations[lang]?.[key] ?? translations['id'][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => useContext(LanguageContext);
