name: Deploy Self Host

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux, vps]

    steps:
      - name: Sync latest code
        run: |
          cd /var/www/w46space
          git fetch origin main
          git reset --hard origin/main

      - name: Rebuild and restart containers
        run: |
           cd /var/www/w46space
          docker compose -p office-rent up -d --build --remove-orphans \
            backend frontend mysql grafana prometheus loki promtail cloudflared docker-stats-exporter

      - name: Check containers
        run: |
          cd /var/www/w46space
          docker compose -p office-rent ps
